name: Deploy to AWS ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ECR_REPOSITORY: your-ecr-repository
      ECS_SERVICE: your-ecs-service
      ECS_CLUSTER: your-ecs-cluster
      CONTAINER_NAME: your-container-name

    steps:
      # Step 1: Checkout code from GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Step 3: Log in to Amazon ECR
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: us-west-2

      # Step 4: Build and push Docker image to ECR
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ env.ECR_REPOSITORY }}:latest

      # Step 5: Deploy to ECS
      - name: Deploy to ECS
        id: deploy
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ecs-task-def.json
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true

      # Step 6: Run integration tests
      - name: Run integration tests
        run: |
          # Add your integration test commands here
          # Example: curl -f http://my-app-endpoint/health

      # Step 7: Rollback if integration tests fail
      - name: Rollback on failure
        if: failure()
        run: |
          echo "Integration tests failed. Rolling back..."
          aws ecs update-service --cluster ${{ env.ECS_CLUSTER }} --service ${{ env.ECS_SERVICE }} --force-new-deployment
